app/urls.py
from django.urls import path
from .views import *

#Nuestro modulo debe ser cargado en el principal

urlpatterns = [
    path('', home, name = "home"),
    path('about-us/', aboutUs, name = "about-us"),
    path('cart/', cart, name = "cart"),
    path('despacho/', despacho, name = "despacho"),
    path('donation/', donation, name = "donation"),
    path('historial/', historial, name = "historial"),
    path('tracking/<codigo>/', tracking, name = "tracking"),
    path('order/', order, name = "order"),
    path('index-log', indexLog, name = "index-log"),
    path('products/', products, name = "products"),
    path('apiProductos/', apiProductos, name = "apiProductos"),
    path('registro/', registro, name = "registro"),
    path('suscribe/', suscribe, name = "suscribe"),
    path('suscribete/', suscribete, name = "suscribete"),
    path('anularSuscripcion/', anularSuscripcion, name = "anularSuscripcion"),
    path('success/', success, name = "success"),
    path('agregar_producto/', agregar_producto, name = "agregar_producto"),
    path('modificarProducto/<cod>', modificarProducto, name = "modificarProducto"),
    path('eliminarProducto/<cod>', eliminarProducto, name = "eliminarProducto"),
    path('listarProductos/', listarProductos, name = "listarProductos"),
    path('perfil/', perfil, name = "perfil"),
    path('cambiarFoto/<rut>/', cambiarFoto, name="cambiarFoto"), 
    path('agregarUsuario/', agregarUsuario, name = "agregarUsuario"),
    path('modificarUsuario/<cod_usuario>', modificarUsuario, name = "modificarUsuario"),
    path('eliminarUsuario/<cod_usuario>', eliminarUsuario, name = "eliminarUsuario"),
    path('listarUsuario/', listarUsuario, name = "listarUsuario"),
    path('eliminarCarro/<id>/', eliminarCarro, name = "eliminarCarro"),
    path('aumentarCarro/<id>/', aumentarCarro, name = "aumentarCarro"),
    path('resetearCarro/', resetearCarro, name = "resetearCarro"),
    path('alterarEstado/<code>/', alterarEstado, name = "alterarEstado"),
]

fundcog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apiapp.urls')), ###Agregar
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Configuraciones de la sección de admin
admin.site.site_title = "Fundacion COG"
admin.site.site_header = "Administración de la Tienda"
admin.site.index_title = "Módulo de Administración"

app/models.py
from django.db import models

# Para extensión modelo User de Django.
from django.contrib.auth.models import User

# Create your models here.

class TipoProducto(models.Model):
    tipo = models.CharField(max_length=20)

    def __str__(self):
        return self.tipo

    class Meta:
        db_table = 'db_tipo_producto'

class Producto(models.Model):
    cod = models.IntegerField(null=False, primary_key=True)
    nombre = models.CharField(max_length=60)
    precio = models.IntegerField()
    stock = models.IntegerField()
    tipo = models.ForeignKey(TipoProducto, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'db_producto'

op_user = [
    [0, "Normal"],
    [1, "Suscrito"]
]

class Registro(models.Model):
    cod_registro = models.IntegerField(null=False, primary_key=True)
    correo = models.EmailField()
    contraseña = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.primer_nombre

    class Meta:
        db_table = 'db_registro'

class Usuario(models.Model):
    cod_usuario = models.IntegerField(null=False, primary_key=True)
    primer_nombre = models.CharField(max_length=30)
    primer_apellido = models.CharField(max_length=30)
    correo = models.EmailField()
    tipo_usuario = models.IntegerField(choices=op_user)
    imagen = models.ImageField(upload_to="suscritos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.primer_nombre

    class Meta:
        db_table = 'db_usuario'

class Sesion(models.Model):
    cod_log = models.IntegerField(null=False, primary_key=True)
    correo = models.EmailField()
    contraseña = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class ItemsCarro(models.Model):
    id_prod = models.IntegerField(null=False)
    nombre_producto = models.CharField(max_length=60)
    precio_producto = models.IntegerField()
    imagen = models.ImageField(upload_to="items_carro", null=True)
    cantidad = models.IntegerField()
    total = models.IntegerField(blank=True)
    usuario = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre_producto

    class Meta:
        db_table = 'db_items_carro'

class Orden(models.Model):
    codigo = models.AutoField(primary_key=True)
    articulos = models.CharField(max_length=300)
    cantidad = models.IntegerField()
    total = models.IntegerField()
    estado_pedido = models.CharField(max_length=50)
    cliente = models.CharField(max_length=30)

    def __str__(self):
        return str(self.codigo)
    
    class Meta:
        db_table = 'db_orden'

class EstadoOrden(models.Model):
    estado = models.CharField(max_length=20)

    def __str__(self):
        return str(self.estado)
    
    class Meta:
        db_table = 'db_estado_orden'

class TipoUsuarioExtra(models.Model):
    tipo = models.CharField(max_length = 20)

    def __str__(self):
        return self.tipo

    class Meta:
        db_table = 'db_tipo_usuario'

class UsuarioExtra(models.Model):
    usuarioDjango = models.OneToOneField(User, on_delete = models.CASCADE,max_length=30)
    run = models.CharField(max_length = 9)
    dv_run = models.CharField(max_length = 1)
    direccion = models.CharField(max_length = 80)
    suscripcion = models.BooleanField()
    imagen = models.ImageField(upload_to="usuarios", null=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.usuarioDjango.username)

    class Meta:
        db_table = 'db_usuario_extra'

app/templates/app/productos/agregar_producto.html
<!--SEGUIMIENTO Y DESPACHO-->
<!DOCTYPE html>
<html lang="en">

{% load static %}


<head>

    <title>Agregar producto(s)</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'app/images/agregar.png' %}" type="image/x-icon">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Slysheet -->
    <link rel="stylesheet" href="{% static 'app/css/me.css' %}">

    <style>
        .bg {
            background-image: url({% static 'app/images/agregar_prod.jpg' %});
            background-position: center center;
            background-repeat: no-repeat;
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-light bg-light fw-bold">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index-log' %}">
                <img src="{% static 'app/images/logo-removebg-preview.png' %}" alt="" width="40" height="34"
                    class="d-inline-block align-text-top">
                Fundacion COG
            </a>
        </div>
    </nav>


    <div class="container w-75 mt-5 rounded shadow">
        {% load crispy_forms_tags %}
        <!-- Parte izquierda del container -->
        <div class="row align-items-stretch">
            <div class="col bg d-none d-lg-block col-md-5 col-lg-5 col-xl-6 rounded">
            </div>

            <!-- Parte derecha del container -->
            <div class="col p-5 rounded-end">
                <div class="text-end">
                    <a href="{% url 'index-log' %}"><img src="{% static 'app/images/logo.png' %}" width="48" alt=""></a>
                </div>

                <h2 class="fw-bold text-center pt-5">Agregar producto(s)</h2>

                <hr class="mb-5">
                <form action="" method="POST" enctype="multipart/form-data">

                    {% csrf_token %}
             
                    <div class="table-responsive">
                        <table>
                            {{ form | crispy }}
                            <hr>
                        </table>
                    </div>

                    <div class="d-grid gap-2 mt-4">
                        <input type="submit" class="btn btn-success" value="Agregar producto">
                    </div>
                </form>

                {{mensaje}}

            </div>
        </div>
    </div>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>

app/templates/app/productos/listarProductos.html
<!--SEGUIMIENTO Y DESPACHO-->
<!DOCTYPE html>
<html lang="en">

{% load static %}

<!-- Eliminar producto Sweetalert -->
<script>
    function eliminarProducto(cod) {
        Swal.fire({
            title: '¿Estás seguro?',
            text: "No podrás deshacer esto",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: '¡Sí, eliminar!',
            cancelButtonText: '¡No, cancelar!',
            reverseButtons: true
        }).then(function (result) {
            if (result.isConfirmed) {
                Swal.fire(
                    '¡Eliminado!',
                    'Tu producto ha sido eliminado.',
                    'success',
                    window.location.href = "/eliminarProducto/" + cod
                )
            } else if (
                /* Read more about handling dismissals below */
                result.dismiss === Swal.DismissReason.cancel
            ) {
                Swal.fire(
                    'Cancelado',
                    'Tu producto imaginario está a salvo :)',
                    'error'
                )
            }
        })
    }
</script>


<head>

    <title>Listar productos</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'app/images/agregar.png' %}" type="image/x-icon">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Slysheet -->
    <link rel="stylesheet" href="{% static 'app/css/me.css' %}">

</head>

<body>

    <nav class="navbar navbar-light bg-light fw-bold">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index-log' %}">
                <img src="{% static 'app/images/logo-removebg-preview.png' %}" alt="" width="40" height="34"
                    class="d-inline-block align-text-top">
                Fundacion COG
            </a>
        </div>
    </nav>

    <div class="container mt-5 rounded shadow">
        <div class="row align-items-stretch">
            <!-- Parte derecha del container -->
            <div class="col p-5 rounded-end">
                <div class="text-end">
                    <a href="{% url 'index-log' %}"><img src="{% static 'app/images/logo.png' %}" width="48" alt=""></a>
                </div>

                <h2 class="fw-bold text-center py-5">Listado de productos</h2>

                <div class="table-responsive">
                    <table class="table table-dark table-striped caption-top mx-auto">
                        <caption>Listado de productos</caption>
                        <thead>
                            <tr>
                                <div class="my-5">
                                    <td>CODIGO</td>
                                    <td>NOMBRE</td>
                                    <td>PRECIO</td>
                                    <td>STOCK</td>
                                    <td>TIPO</td>
                                    <td>IMAGEN</td>
                                    <td>FECHA INGRESO</td>
                                    <td>OPCIONES</td>
                                </div>
                            </tr>
                        </thead>
                        <tbody>

                            {% for aux in listaProductos %}
                            <tr class="align-bottom">
                                <td>{{ aux.cod }}</td>
                                <td>{{ aux.nombre }}</td>
                                <td>{{ aux.precio }}</td>
                                <td>{{ aux.stock }}</td>
                                <td>{{ aux.tipo }}</td>
                                {% if aux.imagen %}
                                <td><img src="{{ aux.imagen.url }}" alt="" width="81" height="80"></td>
                                {% endif %}
                                <td>{{ aux.created_at }}</td>
                                <td class="align-top">
                                    <div class="d-grid gap-2">
                                        {% if perms.app.change_producto %}
                                        <a href="{% url 'modificarProducto' aux.cod %}"
                                            class="btn btn-info my-2 mx-2">Modificar</a>
                                        {% endif %}
                                        {% if perms.app.delete_producto %}
                                        <a href="#" onclick="eliminarProducto({{ aux.cod }})"
                                            class="btn btn-danger my-2 mx-2">Eliminar</a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>


    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="a
        nonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

    {% if messages %}

    {% for m in messages %}

    <script>
        Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "success"
        })
    </script>

    {% endfor %}

    {% endif %}


</body>

</html>

app/templates/app/productos/modificarProducto.html
<!--SEGUIMIENTO Y DESPACHO-->
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

    <title>Modificar producto(s)</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'app/images/modificar.png' %}" type="image/x-icon">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Slysheet -->
    <link rel="stylesheet" href="{% static 'app/css/me.css' %}">

    <style>
        .bg {
            background-image: url({% static 'app/images/modificar.jpg' %});
            background-position: center center;
            background-repeat: no-repeat;
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-light bg-light fw-bold">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index-log' %}">
                <img src="{% static 'app/images/logo-removebg-preview.png' %}" alt="" width="40" height="34"
                    class="d-inline-block align-text-top">
                Fundacion COG
            </a>
        </div>
    </nav>

    <div class="container w-75 mt-5 rounded shadow">
        {% load crispy_forms_tags %}
        <!-- Parte izquierda del container -->
        <div class="row align-items-stretch">
            <div class="col bg d-none d-lg-block col-md-5 col-lg-5 col-xl-6 rounded">
            </div>

            <!-- Parte derecha del container -->
            <div class="col p-5 rounded-end">
                <div class="text-end">
                    <a href="{% url 'index-log' %}"><img src="{% static 'app/images/logo.png' %}" width="48" alt=""></a>
                </div>

                <h2 class="fw-bold text-center pt-5">Modificar producto(s)</h2>
                <hr class="mb-5">

               <form action="" method="POST" enctype="multipart/form-data">

                {% csrf_token %}

                <div class="table-responsive">
                    <table>
                        {{ form | crispy }}
                        <hr>
                    </table>
                </div>

                <div class="d-grid gap-4 mt-4">
                    <input type="submit" class="btn btn-success" value="Modificar">
                </div>

               </form>

               {{mensaje}}

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>