app/urls.py
from django.urls import path
from .views import *

#Nuestro modulo debe ser cargado en el principal

urlpatterns = [
    path('', home, name = "home"),
    path('about-us/', aboutUs, name = "about-us"),
    path('cart/', cart, name = "cart"),
    path('despacho/', despacho, name = "despacho"),
    path('donation/', donation, name = "donation"),
    path('historial/', historial, name = "historial"),
    path('tracking/<codigo>/', tracking, name = "tracking"),
    path('order/', order, name = "order"),
    path('index-log', indexLog, name = "index-log"),
    path('products/', products, name = "products"),
    path('apiProductos/', apiProductos, name = "apiProductos"),
    path('registro/', registro, name = "registro"),
    path('suscribe/', suscribe, name = "suscribe"),
    path('suscribete/', suscribete, name = "suscribete"),
    path('anularSuscripcion/', anularSuscripcion, name = "anularSuscripcion"),
    path('success/', success, name = "success"),
    path('agregar_producto/', agregar_producto, name = "agregar_producto"),
    path('modificarProducto/<cod>', modificarProducto, name = "modificarProducto"),
    path('eliminarProducto/<cod>', eliminarProducto, name = "eliminarProducto"),
    path('listarProductos/', listarProductos, name = "listarProductos"),
    path('perfil/', perfil, name = "perfil"),
    path('cambiarFoto/<rut>/', cambiarFoto, name="cambiarFoto"), 
    path('agregarUsuario/', agregarUsuario, name = "agregarUsuario"),
    path('modificarUsuario/<cod_usuario>', modificarUsuario, name = "modificarUsuario"),
    path('eliminarUsuario/<cod_usuario>', eliminarUsuario, name = "eliminarUsuario"),
    path('listarUsuario/', listarUsuario, name = "listarUsuario"),
    path('eliminarCarro/<id>/', eliminarCarro, name = "eliminarCarro"),
    path('aumentarCarro/<id>/', aumentarCarro, name = "aumentarCarro"),
    path('resetearCarro/', resetearCarro, name = "resetearCarro"),
    path('alterarEstado/<code>/', alterarEstado, name = "alterarEstado"),
]

fundcog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apiapp.urls')), ###Agregar
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Configuraciones de la sección de admin
admin.site.site_title = "Fundacion COG"
admin.site.site_header = "Administración de la Tienda"
admin.site.index_title = "Módulo de Administración"

app/models.py
from django.db import models

# Para extensión modelo User de Django.
from django.contrib.auth.models import User

# Create your models here.

class TipoProducto(models.Model):
    tipo = models.CharField(max_length=20)

    def __str__(self):
        return self.tipo

    class Meta:
        db_table = 'db_tipo_producto'

class Producto(models.Model):
    cod = models.IntegerField(null=False, primary_key=True)
    nombre = models.CharField(max_length=60)
    precio = models.IntegerField()
    stock = models.IntegerField()
    tipo = models.ForeignKey(TipoProducto, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'db_producto'

op_user = [
    [0, "Normal"],
    [1, "Suscrito"]
]

class Registro(models.Model):
    cod_registro = models.IntegerField(null=False, primary_key=True)
    correo = models.EmailField()
    contraseña = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.primer_nombre

    class Meta:
        db_table = 'db_registro'

class Usuario(models.Model):
    cod_usuario = models.IntegerField(null=False, primary_key=True)
    primer_nombre = models.CharField(max_length=30)
    primer_apellido = models.CharField(max_length=30)
    correo = models.EmailField()
    tipo_usuario = models.IntegerField(choices=op_user)
    imagen = models.ImageField(upload_to="suscritos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.primer_nombre

    class Meta:
        db_table = 'db_usuario'

class Sesion(models.Model):
    cod_log = models.IntegerField(null=False, primary_key=True)
    correo = models.EmailField()
    contraseña = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class ItemsCarro(models.Model):
    id_prod = models.IntegerField(null=False)
    nombre_producto = models.CharField(max_length=60)
    precio_producto = models.IntegerField()
    imagen = models.ImageField(upload_to="items_carro", null=True)
    cantidad = models.IntegerField()
    total = models.IntegerField(blank=True)
    usuario = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre_producto

    class Meta:
        db_table = 'db_items_carro'

class Orden(models.Model):
    codigo = models.AutoField(primary_key=True)
    articulos = models.CharField(max_length=300)
    cantidad = models.IntegerField()
    total = models.IntegerField()
    estado_pedido = models.CharField(max_length=50)
    cliente = models.CharField(max_length=30)

    def __str__(self):
        return str(self.codigo)
    
    class Meta:
        db_table = 'db_orden'

class EstadoOrden(models.Model):
    estado = models.CharField(max_length=20)

    def __str__(self):
        return str(self.estado)
    
    class Meta:
        db_table = 'db_estado_orden'

class TipoUsuarioExtra(models.Model):
    tipo = models.CharField(max_length = 20)

    def __str__(self):
        return self.tipo

    class Meta:
        db_table = 'db_tipo_usuario'

class UsuarioExtra(models.Model):
    usuarioDjango = models.OneToOneField(User, on_delete = models.CASCADE,max_length=30)
    run = models.CharField(max_length = 9)
    dv_run = models.CharField(max_length = 1)
    direccion = models.CharField(max_length = 80)
    suscripcion = models.BooleanField()
    imagen = models.ImageField(upload_to="usuarios", null=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.usuarioDjango.username)

    class Meta:
        db_table = 'db_usuario_extra'

app/templates/app/about-us.html
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">

{% load static %}

<head>
  <!-- Site Title-->
  <title>Sobre nosotros</title>

  <meta name="format-detection" content="telephone=no">
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="utf-8">

  <link rel="icon" href="{% static 'app/images/about_icon.png' %}" type="image/x-icon">

  <!-- Stylesheets-->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700%7CRoboto:400,500,700">
  <link rel="stylesheet" href="{% static 'app/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/fonts.css' %}">
  <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

  <style>
    .ie-panel {
      display: none;
      background: #212121;
      padding: 10px 0;
      box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
      clear: both;
      text-align: center;
      position: relative;
      z-index: 1;
    }

    html.ie-10 .ie-panel,
    html.lt-ie-10 .ie-panel {
      display: block;
    }
  </style>

</head>

<body>

  <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img
        src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820"
        alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a>
  </div>

  <!-- Page Loader-->
  <div class="preloader" id="preloader">
    <div class="page-loader-logo">
      <div class="brand">
        <div class="brand__name"><img src="{% static 'app/images/logo.jpg' %}" alt="" width="190" height="50" />
        </div>
      </div>
    </div>
    <div class="page-loader-body">
      <div id="loadingProgressG">
        <div class="loadingProgressG" id="loadingProgressG_1"></div>
      </div>
    </div>
  </div>

  <!-- Page -->
  <div class="page">
    <header class="page-header section">
      <!-- RD Navbar-->
      <div class="rd-navbar-wrap">
        <nav class="rd-navbar rd-navbar-creative" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed"
          data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed"
          data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed"
          data-lg-layout="rd-navbar-fullwidth" data-xl-device-layout="rd-navbar-fullwidth"
          data-xl-layout="rd-navbar-fullwidth" data-xxl-device-layout="rd-navbar-fullwidth"
          data-xxl-layout="rd-navbar-fullwidth" data-stick-up-clone="false" data-md-stick-up-offset="150px"
          data-lg-stick-up-offset="60px" data-md-stick-up="true" data-lg-stick-up="true">
          <div class="rd-navbar-main-outer">
            <div class="rd-navbar-main">
              <!-- RD Navbar Panel-->
              <div class="rd-navbar-panel">
                <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                <!-- RD Navbar Brand-->
                <div class="rd-navbar-brand"><a class="brand" href="/">
                    <div class="brand__name"><img src="{% static 'app/images/logo.jpg' %}" alt="" width="190"
                        height="50" />
                    </div>
                  </a></div>
              </div>
              <!-- RD Navbar Nav-->
              <div class="rd-navbar-nav-wrap">
                <div class="rd-navbar-main-item"><a class="button button-xs button-lighter"
                    href="{% url 'login' %}">Suscribirse</a>
                </div>         
                <!-- RD Navbar Nav-->
                <ul class="rd-navbar-nav">
                  <li><a href="{% url 'home' %}">Inicio</a>
                  </li>
                  <li class="active"><a href="{% url 'about-us' %}">Quiénes somos</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </header>

    <!-- Breadcrumbs -->
    <section class="breadcrumbs-custom bg-image" style="background-image: url({% static 'app/images/about_us.jpg' %});">
      <div class="container">
        <h2 class="breadcrumbs-custom__title">Sobre nosotros</h2>
        <ul class="breadcrumbs-custom__path">
          <li><a href="{% url 'home' %}">Inicio</a></li>
          <li class="active">Quiénes somos</li>
        </ul>
      </div>
    </section>

    <!-- Como empezo todo -->
    <section class="section section-md bg-default">
      <div class="container">
        <div class="row row-70 justify-content-md-center justify-content-xl-between">
          <div class="col-md-10 col-lg-6 col-xl-5">
            <h4>Cómo empezó todo</h4>
            <p>Empezamos siendo un grupo de amigas las cuales soñaban con ayudar a animales callejeros de todo tipo, por
              lo que empezamos vendiendo productos como bandanas, correas e identificaciones hasta lo que somos a día de
              hoy.</p>

            <h4>Nuestra misión</h4>
            <p>Queremos darle la mejor vida posible a nuestras mascotas y a las suyas. Es por eso que dedicamos nuestro
              tiempo en rescatar animales callejeros, y con el dinero recaudado mediante las suscripciones y compra de
              nuestros productos, les damos la mejor vida posible hasta que una familia decida por adoptarlos.</p>
          </div>
          <div class="col-md-10 col-lg-6">
            <div class="row grid-2">
              <div class="col-6"><img src="{% static 'app/images/woman1.jpg' %}" alt="" width="273" height="214" /><img
                  src="{% static 'app/images/woman3.jpg' %}" alt="" width="273" height="214" />
              </div>
              <div class="col-6"><img src="{% static 'app/images/woman2.jpg' %}" alt="" width="273" height="451" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Top Management -->
    <section class="section section-md bg-gray-4">
      <div class="container">
        <!-- Section Header-->
        <div class="section__header">
          <h4>Equipo de trabajo</h4>
          <div class="section__header-element"><a class="link-cta" href="#"></a></div>
        </div>
        <!-- Perfiles del equipo -->
        <div class="row row-30">
          <div class="col-md-6 col-lg-4">
            <!-- Profile creative-->
            <article class="profile-creative">
              <div class="profile-creative__header"><img src="{% static 'app/images/icon1.png' %}" alt="" width="115"
                  height="119" />
              </div>
              <div class="profile-creative__main" data-fixed-height="">
                <p class="profile-creative__title">Millaray Díaz</p>
                <p class="profile-creative__subtitle">Fundadora, CEO</p>
                <div class="profile-creative__element"><a href="mailto:#">m.diaz@fundcog.cl</a></div>
              </div>
            </article>
          </div>
          <div class="col-md-6 col-lg-4">
            <!-- Profile creative-->
            <article class="profile-creative">
              <div class="profile-creative__header"><img src="{% static 'app/images/icon2.jpg' %}" alt="" width="115"
                  height="119" />
              </div>
              <div class="profile-creative__main" data-fixed-height="">
                <p class="profile-creative__title">Mar Kins</p>
                <p class="profile-creative__subtitle">Marketing</p>
                <div class="profile-creative__element"><a href="mailto:#">m.kins@fundcog.cl</a></div>
              </div>
            </article>
          </div>
          <div class="col-md-6 col-lg-4">
            <!-- Profile creative-->
            <article class="profile-creative">
              <div class="profile-creative__header"><img src="{% static 'app/images/icon3.png' %}" alt="" width="115"
                  height="119" />
              </div>
              <div class="profile-creative__main" data-fixed-height="">
                <p class="profile-creative__title">Jessie Chels</p>
                <p class="profile-creative__subtitle">Recursos Humanos</p>
                <div class="profile-creative__element"><a href="mailto:#">j.chels@fundcog.cl</a></div>
              </div>
            </article>
          </div>
        </div>
      </div>
    </section>

    <footer class="footer-classic bg-gray-8">
      <div class="container">
        <div class="footer-classic__main">
          <ul class="list-nav-bordered">
            <li><a href="{% url 'home' %}">Inicio</a></li>
            <li><a href="{% url 'about-us' %}">Sobre nosotros</a>
            </li>
            <li><a href="{% url 'login' %}">Productos</a></li>
            </li>
          </ul>
        </div>
        <div class="divider"></div>
        <div class="footer-classic__aside">
          <div class="row row-20">
            <div class="col-md-6 text-md-left">
              <!-- Rights-->
              <p class="rights"><span>Fundación Cog</span><span>&nbsp;&copy;&nbsp;</span><span
                  class="copyright-year"></span>. Todos los Derechos Reservados.</p>
            </div>
            <div class="col-md-6 text-md-right">
              <ul class="list-inline-xxs">
                <li>
                  <p>Síguenos</p>
                </li>
                <li><a class="icon icon-xs icon-style-modern fa fa-facebook" href="#"></a></li>
                <li><a class="icon icon-xs icon-style-modern fa fa-twitter" href="#"></a></li>
                <li><a class="icon icon-xs icon-style-modern fa fa-instagram" href="#"></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- Global Mailform Output -->
  <div class="snackbars" id="form-output-global"></div>
  <!-- Javascript -->
  <script src="{% static 'app/js/core.min.js' %}"></script>
  <script src="{% static 'app/js/script.js' %}"></script>

</body>

</html>

app/templates/app/apiProductos.html
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">

{% load static %}

<head>

    <title>Productos API</title>

    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">

    <link rel="icon" href="{% static 'app/images/products_icon.png' %}" type="image/x-icon">

    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css"
        href="//fonts.googleapis.com/css?family=Lato:300,400,700%7CRoboto:400,500,700">
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">

    <style>
        .ie-panel {
            display: none;
            background: #212121;
            padding: 10px 0;
            box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
            clear: both;
            text-align: center;
            position: relative;
            z-index: 1;
        }

        html.ie-10 .ie-panel,
        html.lt-ie-10 .ie-panel {
            display: block;
        }
    </style>

</head>

<body>

    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img
                src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820"
                alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a>
    </div>

    <!-- Page Loader-->
    <div class="preloader" id="preloader">
        <div class="page-loader-logo">
            <div class="brand">
                <div class="brand__name"><img src="{% static 'app/images/logo.jpg' %}" alt="" width="190" height="50" />
                </div>
            </div>
        </div>
        <div class="page-loader-body">
            <div id="loadingProgressG">
                <div class="loadingProgressG" id="loadingProgressG_1"></div>
            </div>
        </div>
    </div>

    <!-- Page-->
    <div class="page">
        <header class="page-header section">
            <!-- RD Navbar-->
            <div class="rd-navbar-wrap">
                <nav class="rd-navbar rd-navbar-creative" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed"
                    data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed"
                    data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed"
                    data-lg-layout="rd-navbar-fullwidth" data-xl-device-layout="rd-navbar-fullwidth"
                    data-xl-layout="rd-navbar-fullwidth" data-xxl-device-layout="rd-navbar-fullwidth"
                    data-xxl-layout="rd-navbar-fullwidth" data-stick-up-clone="false" data-md-stick-up-offset="150px"
                    data-lg-stick-up-offset="60px" data-md-stick-up="true" data-lg-stick-up="true">
                    <div class="rd-navbar-main-outer">
                        <div class="rd-navbar-main">
                            <!-- RD Navbar Panel-->
                            <div class="rd-navbar-panel">
                                <button class="rd-navbar-toggle"
                                    data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                                <!-- RD Navbar Brand-->
                                <div class="rd-navbar-brand"><a class="brand" href="{% url 'index-log' %}">
                                        <div class="brand__name"><img src="{% static 'app/images/logo.jpg' %}" alt=""
                                                width="190" height="50" />
                                        </div>
                                    </a></div>
                            </div>
                            <!-- RD Navbar Nav-->
                            <div class="rd-navbar-nav-wrap">
                                <div class="rd-navbar-main-item"><a class="button button-xs button-lighter"
                                        href="{% url 'suscribe' %}">Suscribirse</a>
                                </div>
                                <div class="rd-navbar-main-item"><a class="button button-xs button-lighter mx-4"
                                        href="{% url 'home' %}">Cerrar sesión</a>
                                </div>
                                <!-- RD Navbar Nav-->
                                <ul class="rd-navbar-nav">
                                    <li><a href="{% url 'index-log' %}">Inicio</a>
                                    </li>
                                    {% if perms.app.add_producto %}
                                    <li>
                                        <a href="{% url 'agregar_producto' %}">Agregar producto(s)</a>
                                    </li>
                                    {% endif %}
                                    {% if perms.app.view_producto %}
                                    <li>
                                        <a href="{% url 'listarProductos' %}">Listar producto(s)</a>
                                    </li>
                                    {% endif %}
                                    <li><a href="{% url 'products' %}">Productos</a>
                                    </li>
                                    <li class="active"><a href="{% url 'apiProductos' %}">API</a></li>
                                    <li><a href="{% url 'cart' %}"><i class="icon-sm fa-solid fa-cart-shopping"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <!-- Productos-->
        <section class="section section-md bg-default text-center">
            <div class="container">
                <div class="isotope-wrap isotope-modern-wrap">
                    <!-- Section Header-->
                    <div class="section__header">
                        <h2>Productos</h2>
                        <div class="section__header-element"><a class="link-cta" href="#"></a>
                        </div>
                    </div>
                    <div class="isotope" data-isotope-layout="fitRows" data-isotope-group="products">
                        <div class="row row-offset-2">

                            {% for aux in apiEndpoint %}
                            <div class="col-6 col-md-4 col-lg-3 isotope-item" data-filter="Category 1">
                                <!-- Product-->
                                <article class="product"> <a class="product__image-wrap" href="#">
                                        {% if aux.image %}
                                        <img class="product__image" src="{{ aux.image }}" alt="" width="210"
                                            height="200" /></a>
                                        {% endif %}
                                    <div class="product__main">
                                        <p class="product__title"><a href="#">{{ aux.name }}</a></p>
                                        <p class="product__price mt-2">{{ aux.status }}</p>
                                        <p class="product__price mt-2">{{ aux.species }}</p>
                                    </div>
                                    <div class="product__footer">
                                        <form action="" method="POST">

                                            {% csrf_token %}

                                            <input type="hidden" name="imagen" id="imagen" value="{{ aux.imagen }}">
                                            <input type="hidden" name="nombre_producto" id="nombre_producto"
                                                value="{{ aux.nombre | title }}">
                                            <input type="hidden" name="precio_producto" id="precio_producto"
                                                value="{{ aux.precio }}">
                                            <input type="hidden" name="codigo_producto" id="codigo_producto" value="{{ aux.cod }}">
                                            <input type="submit" style="cursor: pointer;"
                                                class="button button-xs button-gray-2" value="Agregar al carro">

                                        </form>
                                    </div>
                                </article>
                            </div>
                            {% endfor %}

                            

                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer -->
        <footer class="footer-classic bg-gray-8">
            <div class="container">
                <div class="footer-classic__main">
                    <ul class="list-nav-bordered">
                        <li><a href="{% url 'index-log' %}">Inicio</a></li>
                        <li><a href="{% url 'about-us' %}">Sobre nosotros</a></li>
                        <li><a href="{% url 'products' %}">Productos</a></li>
                        </li>
                    </ul>
                </div>
                <div class="divider"></div>
                <div class="footer-classic__aside">
                    <div class="row row-20">
                        <div class="col-md-6 text-md-left">
                            <!-- Rights-->
                            <p class="rights"><span>Fundación Cog</span><span>&nbsp;&copy;&nbsp;</span><span
                                    class="copyright-year"></span>. Todos los Derechos Reservados.</p>
                        </div>
                        <div class="col-md-6 text-md-right">
                            <ul class="list-inline-xxs">
                                <li>
                                    <p>Síguenos</p>
                                </li>
                                <li><a class="icon icon-xs icon-style-modern fa fa-facebook" href="#"></a></li>
                                <li><a class="icon icon-xs icon-style-modern fa fa-twitter" href="#"></a></li>
                                <li><a class="icon icon-xs icon-style-modern fa fa-instagram" href="#"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>


    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{% static 'app/js/core.min.js' %}"></script>
    <script src="{% static 'app/js/script.js' %}"></script>
    <script src="https://kit.fontawesome.com/201353bdaf.js" crossorigin="anonymous"></script>


</body>

</html>

app/templates/app/base-3.html
<!--SEGUIMIENTO Y DESPACHO-->
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

    <title></title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'app/images/despacho.png' %}" type="image/x-icon">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Slysheet -->
    <link rel="stylesheet" href="{% static 'app/css/me.css' %}">

    <style>
        .bg {
            background-image: url({% static 'app/images/despacho_bg.png' %});
            background-position: center center;
            background-repeat: no-repeat;
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-light bg-light fw-bold">
        <div class="container-fluid">
            {% block navbar %}
            {% endblock %}
        </div>
    </nav>

    <div class="container w-75 mt-5 rounded shadow">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>

app/templates/app/seguimiento.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Seguimiento</title>

</head>

<body>

    <ul>
        <li>
            <img src="{% static 'app/images/lupa.jpg' %}">
        </li>
    </ul>
    

</body>

</html>